import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layouts from "./layouts/layouts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PrimePicks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layouts> {children}</Layouts>
      </body>
    </html>
  );
}
